//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XamarinWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class espacio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public espacio()
        {
            this.facturas = new HashSet<factura>();
        }
    
        public int id_espacio { get; set; }
        public string estado { get; set; }
        public System.DateTime hora_entrada { get; set; }
        public System.DateTime hora_salida { get; set; }
        public System.DateTime tiempo_reserva { get; set; }
        public string usuario { get; set; }
        public int parqueo_id_localidad { get; set; }
    
        public virtual parqueo parqueo { get; set; }
        public virtual usuario usuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factura> facturas { get; set; }
    }
}
