//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XamarinWebService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class databaseXamarinEntities : DbContext
    {
        public databaseXamarinEntities()
            : base("name=databaseXamarinEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<espacio> espacios { get; set; }
        public virtual DbSet<factura> facturas { get; set; }
        public virtual DbSet<parqueo> parqueos { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
    }
}
