//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XamarinWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class parqueo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public parqueo()
        {
            this.espacios = new HashSet<espacio>();
        }
    
        public int id_localidad { get; set; }
        public string localidad { get; set; }
        public int cantidad_espacios { get; set; }
        public string nombre_parqueo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<espacio> espacios { get; set; }
    }
}
